FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    wget \
    bzip2 \
    make \
    cmake \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3 \
    python3-pip

RUN wget -q https://github.com/samtools/htslib/releases/download/1.16/htslib-1.16.tar.bz2 && \
    tar jxvf htslib-1.16.tar.bz2 && \
    cd htslib-1.16 && \
    ./configure && \
    make && \
    make install 
    
RUN wget -q https://github.com/cortes-ciriano-lab/savana/archive/refs/tags/0.2.3.tar.gz && \
    tar xvf 0.2.3.tar.gz && \
    cd savana-0.2.3 && \
    pip3 install -r requirements.txt && \
    python3 -m pip install . -vv
