FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    wget \
    bzip2 \
    make \
    cmake \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3 \
    python3-pip

RUN wget -q https://github.com/cortes-ciriano-lab/savana/archive/refs/tags/0.2.3.tar.gz && \
    tar xvf 0.2.3.tar.gz && \
    cd savana-0.2.3 && \
    pip3 install -r requirements.txt && \
    python3 -m pip install . -vv

RUN pip3 install pysam==0.16.0.1
