FROM ubuntu:24.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt update && apt install -y -V ca-certificates lsb-release \
    wget \
    cmake \
    libzstd-dev \
    libzstd-dev \
    libflatbuffers-dev \
    python3 \
    python3-dev \
    python3-pip

RUN pip3 install --upgrade pip && \
    pip3 install pod5
    
