FROM r-base:4.2.2
MAINTAINER aokada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    cpio \
    git \
    wget \
    bzip2 \
    make \
    cmake \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libhdf5-dev \
    libxml2-dev \
    python3 \
    python3-pip \
    python3-dev

RUN pip3 install --upgrade setuptools && \
    pip3 install pysam==0.19.1 && \
    pip3 install numpy==1.23.0 && \
    pip3 install parasail==1.2.4 && \
    pip3 install h5py

RUN wget -q https://github.com/samtools/htslib/releases/download/1.15/htslib-1.15.tar.bz2 && \
    tar jxvf htslib-1.15.tar.bz2 && \
    cd htslib-1.15 && \
    ./configure && \
    make && \
    make install 

RUN wget -q http://ftp.debian.org/debian/pool/main/m/mafft/mafft_7.407-2_amd64.deb && \
    dpkg -i mafft_7.407-2_amd64.deb
    
RUN wget -q https://github.com/isovic/racon/releases/download/1.4.3/racon-v1.4.3.tar.gz && \
    tar zxvf racon-v1.4.3.tar.gz && \
    cd racon-v1.4.3 && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make && make install

RUN wget -q https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/archive/v1.1.tar.gz && \
    tar zxvf v1.1.tar.gz && \
    cd Complete-Striped-Smith-Waterman-Library-1.1/src && \
    gcc -Wall -O3 -pipe -fPIC -shared -rdynamic -o libssw.so ssw.c ssw.h

ENV LD_LIBRARY_PATH /Complete-Striped-Smith-Waterman-Library-1.1/src:$LD_LIBRARY_PATH

RUN wget -q https://github.com/lh3/minimap2/releases/download/v2.24/minimap2-2.24.tar.bz2 && \
    tar jxvf minimap2-2.24.tar.bz2 && \
    cd minimap2-2.24 && \
    make

ENV PATH $PATH:/minimap2-2.24

RUN git clone https://github.com/friend1ws/nanomonsv.git && \
    cd nanomonsv && \
    python3 -m pip install . 

RUN wget -q https://github.com/lh3/bwa/releases/download/v0.7.13/bwakit-0.7.13_x64-linux.tar.bz2 && \
    tar jxvf bwakit-0.7.13_x64-linux.tar.bz2

ENV PATH /bwa.kit:$PATH

# RepeatMasker
RUN wget -q https://www.repeatmasker.org/RepeatMasker/RepeatMasker-4.1.2-p1.tar.gz && \
    tar zxvf RepeatMasker-4.1.2-p1.tar.gz && \
    mv RepeatMasker /usr/local/

ENV PATH /usr/local/RepeatMasker:$PATH

RUN wget -q https://github.com/Benson-Genomics-Lab/TRF/archive/refs/tags/v4.09.1.tar.gz && \
    tar zxvf v4.09.1.tar.gz && \
    cd TRF-4.09.1/ && \
    ./configure && \
    make && make install
    
RUN wget -q ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.11.0/ncbi-blast-2.11.0+-src.tar.gz && \
    tar xzvf ncbi-blast-2.11.0+-src.tar.gz && \
    cd ncbi-blast-2.11.0+-src/ && \
    wget -q http://www.repeatmasker.org/isb-2.11.0+-rmblast.patch.gz && \
    gunzip isb-2.11.0+-rmblast.patch.gz && \
    sed -i "s#https://www.repeatmasker.org/rmblast/stat#https://localhost/#" isb-2.11.0+-rmblast.patch && \
    patch -p1 < isb-2.11.0+-rmblast.patch && \
    cd c++/ && \
    ./configure  --with-mt --without-debug --without-krb5 --without-openssl --with-projects=scripts/projects/rmblastn/project.lst --prefix=/usr/local/rmblast-2.11.0 && \
    make -j "$(nproc)" && \
    make install

ENV PATH /usr/local/rmblast-2.11.0:$PATH

RUN cd /usr/local/RepeatMasker && \
    perl ./configure \
        -trf_prgm /usr/local/bin/trf \
        -rmblast_dir /usr/local/rmblast-2.11.0/bin \
        -hmmer_dir /usr/local/hmmer/bin \
        -crossmatch_dir /usr/local/phrap \
        -abblast_dir /usr/local/abblast \
        -libdir /usr/local/RepeatMasker/Libraries \
        -default_search_engine rmblast

RUN Rscript -e "install.packages('ggrepel')" && \
    Rscript -e "install.packages('tidyverse')"
