FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    g++ \
    cmake \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libhdf5-dev \
    libzstd-dev

WORKDIR /tools
RUN wget -q https://github.com/samtools/samtools/releases/download/1.16/samtools-1.16.tar.bz2 && \
    tar jxvf samtools-1.16.tar.bz2 && \
    rm samtools-1.16.tar.bz2 && \
    cd samtools-1.16/htslib-1.16 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install

RUN git clone --recursive https://github.com/jts/nanopolish.git && \
    cd nanopolish && \
    git checkout v0.14.0 && \
    make all

RUN wget -q https://github.com/nanoporetech/vbz_compression/archive/refs/tags/1.0.2.tar.gz && \
    tar xzvf 1.0.2.tar.gz && \
    rm 1.0.2.tar.gz && \
    cd vbz_compression-1.0.2 && mkdir build && cd build && \
    cmake -D CMAKE_BUILD_TYPE=Release -D ENABLE_CONAN=OFF -D ENABLE_PERF_TESTING=OFF -D ENABLE_PYTHON=OFF .. && \
    make -j

ENV HDF5_PLUGIN_PATH /usr/local/hdf5/lib/plugin
