FROM ubuntu:24.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    pigz \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3 \
    python3-venv \
    python3-pip

RUN pip install Spandas --break-system-packages && \
    git clone https://github.com/SigProfilerSuite/SigProfilerExtractor.git && \
    cd SigProfilerExtractor && \
    pip install . --break-system-packages

RUN python3 -c 'from SigProfilerMatrixGenerator import install as genInstall; genInstall.install("GRCh38")'
