FROM ubuntu:22.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    pigz \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3 \
    python3-pip

RUN pip install "pandas<2.0.0" Spandas SigProfilerExtractor

RUN python3 -c 'from SigProfilerMatrixGenerator import install as genInstall; genInstall.install("GRCh38")'
