FROM ubuntu:16.04
MAINTAINER aokad <aokada@ncc.go.jp> 

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python \
    python-pip

# for blat
RUN apt-get update && apt-get install -y \
    libkrb5-3 \
    libpng12-0
    
WORKDIR /tools

RUN wget https://github.com/samtools/htslib/releases/download/1.3/htslib-1.3.tar.bz2 && \
    tar jxvf htslib-1.3.tar.bz2 && \
    cd htslib-1.3 && \
    ./configure && \
    make && \
    make install

RUN echo "build BLAT v.35" && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/userApps.v359.src.tgz && \
    tar -xzvf userApps.v359.src.tgz && \
    rm -f userApps.v359.src.tgz && \
    cd userApps && \
    make && make install

RUN pip install --upgrade pip && \
    pip install --upgrade setuptools && \
    pip install annot_utils==0.2.1 && \
    pip install pysam==0.9.1.4 && \
    pip install numpy==1.15.1 && \
    pip install scipy==1.1.0 && \
    pip install genomon_sv==0.6.1b1 && \
    \ #pip install primer3-py==0.5.5 && \
    pip install sv_utils==0.5.1
