FROM dfam/tetools:1.94
MAINTAINER aokada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    cpio \
    git \
    wget \
    bzip2 \
    make \
    cmake \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libhdf5-dev \
    libxml2-dev \
    python3 \
    python3-pip \
    python3-dev
    
RUN wget -q https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.14.1/ncbi-blast-2.14.1+-src.tar.gz && \
    tar xzvf ncbi-blast-2.14.1+-src.tar.gz && \
    cd ncbi-blast-2.14.1+-src/ && \
    wget -q https://www.repeatmasker.org/rmblast/isb-2.14.1+-rmblast.patch.gz && \
    gunzip isb-2.14.1+-rmblast.patch.gz && \
    sed -i "s#https://www.repeatmasker.org/rmblast/stat#https://localhost/#" isb-2.14.1+-rmblast.patch && \
    patch -p1 < isb-2.14.1+-rmblast.patch && \
    cd c++/ && \
    ./configure  --with-mt --without-debug --without-krb5 --without-openssl --with-projects=scripts/projects/rmblastn/project.lst --prefix=/usr/local/rmblast-2.14.1 && \
    make -j "$(nproc)" && \
    make install

