FROM python:3.12
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

RUN apt-get update && apt-get install -y --no-install-recommends \
    r-base

WORKDIR /tools 
RUN wget -q https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2 && \
    tar jxvf samtools-1.21.tar.bz2 && \
    cd samtools-1.21/htslib-1.21 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install

RUN wget -q https://github.com/lh3/minimap2/releases/download/v2.28/minimap2-2.28.tar.bz2 && \
    tar jxvf minimap2-2.28.tar.bz2 && \
    cd minimap2-2.28 && \
    make
    
RUN wget -q https://github.com/logsdon-lab/NucFlag/archive/refs/tags/v0.2.0.zip && \
    unzip v0.2.0.zip && \
    cd NucFlag-0.2.0 && pip install . && \
    pip install -r requirements.txt

RUN wget -q https://github.com/mrvollger/NucFreq/archive/refs/tags/v0.1.zip && \
    unzip v0.1.zip && \
    pip install numpy pysam pandas matplotlib seaborn

RUN Rscript -e "install.packages('ggplot2')" && \
    Rscript -e "install.packages('directlabels')" && \
    Rscript -e "install.packages('dplyr')" && \
    Rscript -e "install.packages('RColorBrewer')" && \
    Rscript -e "install.packages('reshape2')" && \
    Rscript -e "install.packages('tidyr')" && \
    Rscript -e "install.packages('ggsci')" && \
    Rscript -e "install.packages('zoo')"
    
CMD ["/bin/bash"]
