FROM ubuntu:18.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    python3 \
    python3-pip 

RUN wget https://github.com/Genomon-Project/GenomonVirusChecker/archive/refs/tags/v0.1.0.zip && \
    unzip v0.1.0.zip && \
    cd GenomonVirusChecker-0.1.0 && \
    python3 setup.py build install
    
CMD ["/bin/bash"]
