FROM ubuntu:18.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    git \
    wget \
    rsync \
    bzip2 \
    make \
    gcc \
    unzip \
    vim \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python \
    python-pip \
    python3 \
    python3-pip

WORKDIR /tools
RUN wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2 && \
    tar jxvf samtools-1.11.tar.bz2 && \
    cd samtools-1.11/htslib-1.11 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install

RUN wget https://github.com/samtools/bcftools/releases/download/1.11/bcftools-1.11.tar.bz2 && \
    tar jxvf bcftools-1.11.tar.bz2 && \
    cd bcftools-1.11 && ./configure && make && make install

RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.27.0/bedtools-2.27.0.tar.gz && \
    tar -zxvf bedtools-2.27.0.tar.gz && \
    cd bedtools2 && make && make install
    
RUN  mkdir -p /data/scripts /data/bin && \
 chmod 755 /data/scripts /data/bin && \
 rsync -a rsync://hgdownload.soe.ucsc.edu/genome/admin/exe/linux.x86_64/ /data/bin/ && \
 git archive --remote=git://genome-source.soe.ucsc.edu/kent.git \
  --prefix=kent/ HEAD src/hg/utils/automation \
 | tar vxf - -C /data/scripts --strip-components=5 \
  --exclude='kent/src/hg/utils/automation/incidentDb' \
  --exclude='kent/src/hg/utils/automation/configFiles' \
  --exclude='kent/src/hg/utils/automation/ensGene' \
  --exclude='kent/src/hg/utils/automation/genbank' \
  --exclude='kent/src/hg/utils/automation/lastz_D' \
  --exclude='kent/src/hg/utils/automation/openStack' && \
 wget -O /data/bin/bedSingleCover.pl 'http://genome-source.soe.ucsc.edu/gitlist/kent.git/raw/master/src/utils/bedSingleCover.pl'
     
ENV PATH /data/bin:/data/bin/blat:/data/scripts:$PATH
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH

RUN wget https://github.com/Genomon-Project/GenomonVirusChecker/archive/refs/tags/v0.1.0.zip && \
    unzip v0.1.0.zip && \
    cd GenomonVirusChecker-0.1.0 && \
    python setup.py build install && \
    cd resource && \
    bash prepareVirus.sh
    
CMD ["/bin/bash"]
