FROM ubuntu:20.04
MAINTAINER Yuichi Shiraishi <friend1ws@gmail.com> 
MAINTAINER Kenichi Chiba <kchiba@hgc.jp>
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3-pip

RUN wget https://github.com/samtools/htslib/releases/download/1.16.1/htslib-1.16.1.tar.bz2 && \
    tar jxvf htslib-1.16.1.tar.bz2 && \
    cd htslib-1.16.1 && \
    ./configure && \
    make && \
    make install

RUN wget https://github.com/samtools/samtools/releases/download/1.16.1/samtools-1.16.1.tar.bz2 && \
    tar jxvf samtools-1.16.1.tar.bz2 && \
    cd samtools-1.16.1 && \
    ./configure --without-curses && \
    make && \
    make install
    
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools

RUN pip3 install annot_utils
RUN pip3 install pysam
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install genomon-sv
RUN pip3 install edlib

# sv_utils
RUN pip3 install sv_utils
RUN pip3 install primer3-py
