FROM ubuntu:24.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

RUN apt-get update && apt-get install -y \
    wget \
    python3 \
    python3-dev \
    python3-pip
    
RUN wget https://github.com/ablab/quast/releases/download/quast_5.3.0/quast-5.3.0.tar.gz && \
    tar xvf quast-5.3.0.tar.gz  && \
    cd quast-5.3.0 && \
    pip install . --break-system-packages
