FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /opt

RUN apt-get update && apt-get install -y \
    git \
    wget \
    curl \
    bzip2 \
    make \
    cmake \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    graphviz-dev \
    python3 \
    python3-pip

WORKDIR /tools
RUN wget -q https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2 && \
    tar jxvf samtools-1.18.tar.bz2 && \
    cd samtools-1.18/htslib-1.18 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install
    
RUN pip install pygraphviz && \
    pip install pydot && \
    pip install matplotlib && \
    pip install biopython && \
    pip install numpy && \
    pip install pysam && \
    pip install networkx

RUN git clone https://github.com/KolmogorovLab/Severus && \
    cd Severus && python3 setup.py install
