FROM python:3.7.4-buster

MAINTAINER Ai Okada <aokada@ncc.go.jp>

WORKDIR /tools

RUN apt-get -y update && \
    apt-get install -y wget git tar
    
RUN wget --trust-server-names "https://sourceforge.net/projects/subread/files/subread-1.5.2/subread-1.5.2-Linux-x86_64.tar.gz" && \
    tar -zxvf subread-1.5.2-Linux-x86_64.tar.gz && \
    cp -r subread-1.5.2-Linux-x86_64/bin/* /usr/local/bin/

RUN git clone https://github.com/friend1ws/simple_exp.git
