FROM ubuntu:24.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    cmake \
    libzstd-dev \
    libflatbuffers-dev \
    python3 \
    python3-dev \
    python3-pip

RUN wget -q https://github.com/samtools/samtools/releases/download/1.23/samtools-1.23.tar.bz2 && \
    tar jxvf samtools-1.23.tar.bz2 && \
    cd samtools-1.23/htslib-1.23 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install

RUN wget -q https://github.com/samtools/bcftools/releases/download/1.23/bcftools-1.23.tar.bz2 && \
    tar jxvf bcftools-1.23.tar.bz2 && \
    cd bcftools-1.23 && ./configure && make && make install

RUN wget -q https://github.com/lh3/minimap2/releases/download/v2.30/minimap2-2.30_x64-linux.tar.bz2 && \
    tar jxvf minimap2-2.30_x64-linux.tar.bz2

RUN pip install Liftoff --break-system-packages

ENV PATH $PATH:/usr/local/minimap2-2.30_x64-linux
