FROM ubuntu:22.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev
    
RUN wget -q https://github.com/samtools/samtools/releases/download/1.19/samtools-1.19.tar.bz2 && \
    tar jxvf samtools-1.19.tar.bz2 && \
    cd samtools-1.19/htslib-1.19 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install

RUN wget -q https://github.com/samtools/bcftools/releases/download/1.19/bcftools-1.19.tar.bz2 && \
    tar jxvf bcftools-1.19.tar.bz2 && \
    cd bcftools-1.19 && ./configure && make && make install

RUN wget -q https://github.com/lh3/minimap2/releases/download/v2.28/minimap2-2.28_x64-linux.tar.bz2
    tar jxvf minimap2-2.28_x64-linux.tar.bz2 && \
    cd minimap2-2.28_x64-linux && \
    make

ENV PATH $PATH:/usr/local/minimap2-2.28_x64-linux
ENV PATH $PATH:/usr/local/samtools-1.9/bin
