FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    g++ \
    cmake \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libhdf5-dev \
    libzstd-dev

WORKDIR /tools
RUN wget -q https://github.com/samtools/samtools/releases/download/1.16/samtools-1.16.tar.bz2 && \
    tar jxvf samtools-1.16.tar.bz2 && \
    rm samtools-1.16.tar.bz2 && \
    cd samtools-1.16/htslib-1.16 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install

RUN git clone --recursive https://github.com/jts/nanopolish.git && \
    cd nanopolish && \
    git checkout v0.14.0 && \
    wget -q https://raw.githubusercontent.com/ncc-ccat-gap/module_box_aokad/master/20230320-nanopolish_debug/set_debug_flag.patch && \
    git set_debug_flag.patch && \
    make all

RUN wget -q https://github.com/nanoporetech/vbz_compression/releases/download/v1.0.1/ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz && \
    tar xzvf  ont-vbz-hdf-plugin-1.0.1-Linux-x86_64.tar.gz 
    
ENV HDF5_PLUGIN_PATH /tools/ont-vbz-hdf-plugin-1.0.1-Linux/usr/local/hdf5/lib/plugin/
