FROM ubuntu:22.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update -y && apt-get install -y \
    g++ \
    make \
    cmake \
    libbz2-dev \
    zlib1g-dev \
    ragel \
    wget

WORKDIR /tools

# vcf_validator
RUN mkdir vcf_validator && cd vcf_validator && \
    wget https://github.com/EBIvariation/vcf-validator/releases/tag/v0.9.4/vcf_validator_linux && \
    chmod +x vcf_validator_linux
