FROM ubuntu:18.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    sqlite3 \
    python3.8
    
RUN echo 'alias python=/usr/bin/python3.8' >> ~/.bashrc

CMD ["/bin/bash"]
