FROM python:3.8.10-buster

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    less vim sqlite3
    
RUN git clone https://github.com/aokad/otomo.git && \
    cd otomo && \
    python3.8 setup.py build install

CMD ["/bin/bash"]
