FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    pigz \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3 \
    python3-pip

RUN pip3 install --upgrade pip && \
    pip3 install pysam==0.20.0 && \
    pip3 install cffi==1.15.0 && \
    pip3 install modbampy

RUN git clone -b v0.10.0 --recursive https://github.com/epi2me-labs/modbam2bed.git && \
    mkdir /tools/ && mv /modbam2bed /tools/modbam2bed && \
    cd /tools/modbam2bed && make   
