FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /opt

RUN apt-get update && apt-get install -y \
    wget \
    git \
    vim \
    curl
    
RUN /bin/bash -c "$(curl -fsSL https://exaloop.io/install.sh)"

ENV PATH /root/.codon/bin:$PATH
