FROM aokad/star:2.7.1a
# based on https://raw.githubusercontent.com/ncc-ccat-gap/module_box_aokad/master/20190925-star/Dockerfile.txt

MAINTAINER Ai Okada <aokada@ncc.go.jp>

##########
## STAR

RUN wget https://github.com/alexdobin/STAR/archive/2.7.2b.tar.gz && \
    tar xzvf 2.7.2b.tar.gz && \
    mv STAR-2.7.2b/bin/Linux_x86_64_static/STAR /usr/local/bin

##########
## sequeeze

RUN https://github.com/aokad/sequeeze/archive/master.zip && \
    unzip master.zip && \
    cd sequeeze-master && \
    make && make install

