FROM python:3.10.6-buster

MAINTAINER ken-ichi chiba <kchiba@hgc.jp>

RUN apt-get -y update
RUN apt-get install -y wget pigz

WORKDIR /usr/local

RUN wget -q https://github.com/fritzsedlazeck/SURVIVOR/archive/v1.0.6.tar.gz && \
    tar xzvf v1.0.6.tar.gz && \
    cd SURVIVOR-1.0.6/Debug && \
    make

RUN wget -q https://github.com/lh3/minimap2/releases/download/v2.24/minimap2-2.24.tar.bz2 && \
    tar jxvf minimap2-2.24.tar.bz2 && \
    cd minimap2-2.24 && \
    make

RUN wget -q https://sourceforge.net/projects/samtools/files/samtools/1.16/samtools-1.16.tar.bz2 && \
    tar xjvf samtools-1.16.tar.bz2 && \
    rm -f samtools-1.16.tar.bz2 && \
    cd samtools-1.16 && \
    make && make install

RUN wget -q https://sourceforge.net/projects/samtools/files/samtools/1.16/htslib-1.16.tar.bz2 && \
    tar xvf htslib-1.16.tar.bz2 && \
    rm -f htslib-1.16.tar.bz2 && \
    cd htslib-1.16 && \
    make && make install

RUN wget -q https://sourceforge.net/projects/samtools/files/samtools/1.16/bcftools-1.16.tar.bz2 && \
    tar xvf bcftools-1.16.tar.bz2 && \
    rm -f bcftools-1.16.tar.bz2 && \
    cd bcftools-1.16 && \
    ./configure && \
    make && make install
    
RUN wget -q https://github.com/bcgsc/NanoSim/archive/v2.6.0.tar.gz && \
    tar xzvf v2.6.0.tar.gz && \
    cd NanoSim-2.6.0/src && \
    grep -l 'from sklearn.externals import joblib' *py  | xargs sed -i.bak -e 's;from sklearn.externals import joblib;import joblib;g'

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN pip install six==1.16.0
RUN pip install pysam==0.19.1
RUN pip install numpy==1.19.5
RUN pip install scipy==1.5.4
RUN pip install HTSeq==2.0.2
RUN pip install scikit-learn==0.24.2

ENV PATH $PATH:/usr/local/SURVIVOR-1.0.6/Debug
ENV PATH $PATH:/usr/local/minimap2-2.17
