FROM ubuntu:24.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev
    
RUN wget -q https://github.com/samtools/samtools/releases/download/1.23/samtools-1.23.tar.bz2 && \
    tar jxvf samtools-1.23.tar.bz2 && \
    cd samtools-1.23/htslib-1.23 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install

RUN wget -q https://github.com/samtools/bcftools/releases/download/1.23/bcftools-1.23.tar.bz2 && \
    tar jxvf bcftools-1.23.tar.bz2 && \
    cd bcftools-1.23 && ./configure && make && make install

RUN wget -q https://github.com/lh3/yak/archive/refs/tags/v0.1.tar.gz && \
    tar xvf v0.1.tar.gz && \
    cd yak-0.1 && make   
    
ENV PATH $PATH:/usr/local/yak-0.1
