FROM ubuntu:18.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    make \
    gcc \
    g++

WORKDIR /tools

RUN wget https://github.com/lh3/seqtk/archive/refs/tags/v1.3.zip && \
    unzip v1.3.zip && \
    cd seqtk-1.3 && \
    make && make install

CMD ["/bin/bash"]


