FROM ubuntu:22.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update -y && apt-get install -y \
    g++ \
    libbz2-dev \
    liblzma-dev \
    make \
    cmake \
    openjdk-8-jre \
    dpkg-dev \
    git \
    ragel \
    tar \
    unzip \
    wget \
    zlib1g-dev && \
    python2 \
    python2-dev \
    python-pip && \
    ln -s /usr/bin/python2 /usr/local/bin/python

WORKDIR /tools

# vcf_validator
RUN mkdir vcf_validator && cd vcf_validator \
    && wget https://github.com/EBIvariation/vcf-validator/releases/tag/v0.9.5/vcf_validator_linux \
    && chmod 750 vcf_validator_linux 

# gatk
RUN wget https://github.com/broadinstitute/gatk/releases/download/4.1.0.0/gatk-4.1.0.0.zip && \
    unzip gatk-4.1.0.0.zip && \
    rm -f gatk-4.1.0.0.zip

# vcflib
RUN git clone --recursive https://github.com/vcflib/vcflib.git \
    && cd vcflib \
    && make
