FROM debian:10.9

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

RUN pip3 install virtualenv && \
    virtualenv -p python3 venv && \
    . venv/bin/activate && \
    pip3 install ont-fast5-api==0.3.2
    
