FROM debian:10.9

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget \
    unzip

RUN pip3 install virtualenv && \
    virtualenv -p python3 venv && \
    . venv/bin/activate && \
    wget https://github.com/nanoporetech/ont_fast5_api/archive/refs/tags/release_0.3.2.zip && \
    unzip release_0.3.2.zip && \
    cd ont_fast5_api-release_0.3.2/ && \
    python setup.py build install
    
