FROM condaforge/mambaforge:latest

MAINTAINER Ai Okada <aokada@ncc.go.jp>

# Install all tools via conda/mamba
RUN mamba install -y -c bioconda -c conda-forge \
        stringdecomposer=1.1.2 \
        samtools=1.21 \
        bedtools=2.31.1 \
        python=3.10 \
        gawk \
    && mamba clean -afy
    

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        gawk \
        git \
        wget \
        bzip2 \
        gcc \
        make \
        pigz \
        zlib1g-dev \
        libbz2-dev \
        libcurl4-openssl-dev \
        liblzma-dev \
        libncurses5-dev \
        libssl-dev \
        graphviz-dev \
        ca-certificates \
        python3 \
        python3-dev \
        python3-pip \
        r-base \
        autoconf \
        automake \
        libtool

RUN pip install biopython==1.82 joblib networkx edlib pygraphviz && \
    git clone https://github.com/ablab/HORmon.git HORmon_src && \
    pip install ./HORmon_src

RUN wget https://sourceforge.net/projects/argtable/files/argtable/argtable-2.13/argtable2-13.tar.gz/download -O argtable2-13.tar.gz && \
    tar xzf argtable2-13.tar.gz && \
    cd argtable2-13 && \
    ./configure && \
    make -j4 && make install

RUN wget https://github.com/GSLBiotech/clustal-omega/archive/refs/tags/1.2.4.tar.gz && \
    tar xzf 1.2.4.tar.gz && \
    cd clustal-omega-1.2.4 && \
    autoreconf -i -f && \
    ./configure && \
    make -j4 && make install
