FROM ubuntu:22.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    ca-certificates
    
# --- agc 3.2 ---
RUN wget -q https://github.com/refresh-bio/agc/releases/download/v3.2.2/agc-v3.2.2-x64_linux.tar.gz && \
    tar xzf agc-v3.2.2-x64_linux.tar.gz && \
    cp agc /usr/local/bin/
    
