FROM ubuntu:22.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C

ARG SAMTOOLS_VERSION=1.14
ARG MINIMAP2_VERSION=2.28

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        zlib1g-dev \
        libbz2-dev \
        liblzma-dev \
        libcurl4-openssl-dev \
        libncurses5-dev \
        python3 \
        wget \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install samtools
RUN wget -q https://github.com/samtools/samtools/releases/download/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2 \
    && tar xjf samtools-${SAMTOOLS_VERSION}.tar.bz2 \
    && cd samtools-${SAMTOOLS_VERSION} \
    && ./configure --prefix=/usr/local \
    && make -j$(nproc) \
    && make install \
    && cd .. && rm -rf samtools-${SAMTOOLS_VERSION}*

# Install minimap2
RUN wget -q https://github.com/lh3/minimap2/releases/download/v${MINIMAP2_VERSION}/minimap2-${MINIMAP2_VERSION}_x64-linux.tar.bz2 \
    && tar xjf minimap2-${MINIMAP2_VERSION}_x64-linux.tar.bz2 \
    && cp minimap2-${MINIMAP2_VERSION}_x64-linux/minimap2 /usr/local/bin/ \
    && rm -rf minimap2-${MINIMAP2_VERSION}*

