FROM rocker/rstudio:4.5.1
MAINTAINER aokada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    wget \
    git \
    bzip2 \
    make \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libglpk-dev
    
RUN Rscript -e "install.packages('BiocManager')"
RUN Rscript -e "BiocManager::install()"
RUN Rscript -e "BiocManager::install('NanoStringNCTools')"
RUN Rscript -e "BiocManager::install('GeomxTools')"
RUN Rscript -e "BiocManager::install('GeoMxWorkflows')"
