FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    wget \
    g++ \
    cmake \
    libboost-all-dev \
    pandoc \
    zlib1g-dev \
    libbz2-dev \
    libsqlite3-dev

RUN git clone https://github.com/data61/gossamer.git && \
    mkdir gossamer/build && cd gossamer/build && \
    cmake -DBUILD_tests=OFF .. && \
    make && make install
    
