FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    wget \
    bzip2

RUN wget https://github.com/arq5x/poretools/archive/refs/tags/v0.6.0.tar.gz && \
    tar xvf v0.6.0.tar.gz && \
    cd poretools-0.6.0 && \
    python setup.py install
