FROM python:2.7.18-buster
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN pip install pandas h5py matplotlib seaborn

RUN wget -q https://github.com/arq5x/poretools/archive/refs/tags/v0.6.0.tar.gz && \
    tar xvf v0.6.0.tar.gz && \
    cd poretools-0.6.0 && \
    python setup.py install
