FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /opt

RUN apt-get update && apt-get install -y \
    sudo \
    wget \
    git
    
ENV PATH /opt/miniconda3/bin:$PATH

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    sh Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 && \
    rm -r Miniconda3-latest-Linux-x86_64.sh && \
    conda update -n base -c defaults conda && \
    conda init

RUN git clone -b v1.0.16 https://github.com/maickrau/GraphAligner.git && \
    cd GraphAligner && \
    git submodule update --init --recursive && \
    conda env create -f CondaEnvironment.yml
#    conda activate GraphAligner && \
#    conda install -y make && \
#    make bin/GraphAligner
    
CMD ["/bin/bash"]
