FROM ubuntu:24.04
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc

RUN git clone https://github.com/lh3/TRF-mod && \
  cd TRF-mod && \
  git checkout 3e891db && \
  make -f compile.mak
  
