FROM centos:7
MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    yum -y update && \
    yum -y install wget git bgzip2 gcc gcc-c++ make && \
    yum clean all

RUN git clone https://github.com/lh3/TRF-mod && \
  cd TRF-mod && \
  git checkout 3e891db && \
  make -f compile.mak
