FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    pigz \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python \
    python3 \
    python3-pip

WORKDIR /tool
RUN wget -q https://sourceforge.net/projects/samtools/files/samtools/1.16/samtools-1.16.tar.bz2 && \
    tar xjvf samtools-1.16.tar.bz2 && \
    rm -f samtools-1.16.tar.bz2 && \
    cd samtools-1.16 && \
    ./configure --without-curses && \
    make && make install

RUN wget https://github.com/samtools/bcftools/releases/download/1.16/bcftools-1.16.tar.bz2 && \
    tar xjvf bcftools-1.16.tar.bz2 && \
    rm -f bcftools-1.16.tar.bz2 && \
    cd bcftools-1.16 && \
    ./configure && \
    make && make install

RUN wget -nc https://sourceforge.net/projects/samtools/files/samtools/1.16/htslib-1.16.tar.bz2 && \
    tar xjvf htslib-1.16.tar.bz2 && \
    rm -f htslib-1.16.tar.bz2 && \
    cd htslib-1.16 && \
    ./configure && \
    make && make install

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install cython
RUN pip3 install pysam
RUN pip3 install pandas

