FROM ubuntu:18.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python \
    python3 \
    python3-pip

WORKDIR /tools

##########
# samtools etc

RUN wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2 && \
    tar jxvf samtools-1.11.tar.bz2 && \
    cd samtools-1.11/htslib-1.11 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install

RUN wget https://github.com/samtools/bcftools/releases/download/1.11/bcftools-1.11.tar.bz2 && \
    tar jxvf bcftools-1.11.tar.bz2 && \
    cd bcftools-1.11 && ./configure && make && make install

RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.27.0/bedtools-2.27.0.tar.gz && \
    tar -zxvf bedtools-2.27.0.tar.gz && \
    cd bedtools2 && make && make install

##########
# minimap

RUN wget https://github.com/lh3/minimap2/releases/download/v2.17/minimap2-2.17.tar.bz2 && \
    tar jxvf minimap2-2.17.tar.bz2 && \
    cd  minimap2-2.17 && make && mv minimap2 /usr/local/bin

##########
# nanopolish

RUN git clone --recursive https://github.com/jts/nanopolish.git && \
    cd nanopolish && \
    make all 

##########
# nanomonsv

RUN wget http://ftp.debian.org/debian/pool/main/m/mafft/mafft_7.407-2_amd64.deb && \
    dpkg -i mafft_7.407-2_amd64.deb
    
RUN apt-get install -y cmake
RUN wget https://github.com/isovic/racon/releases/download/1.4.3/racon-v1.4.3.tar.gz && \
    tar zxvf racon-v1.4.3.tar.gz && \
    cd racon-v1.4.3 && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    make && make install

RUN pip3 install --upgrade setuptools

RUN pip3 install pysam==0.15.2
RUN pip3 install numpy==1.15.1
RUN pip3 install parasail==1.2

RUN wget https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/archive/v1.1.tar.gz && \
    tar zxvf v1.1.tar.gz && \
    cd Complete-Striped-Smith-Waterman-Library-1.1/src && \
    gcc -Wall -O3 -pipe -fPIC -shared -rdynamic -o libssw.so ssw.c ssw.h

ENV LD_LIBRARY_PATH /Complete-Striped-Smith-Waterman-Library-1.1/src:$LD_LIBRARY_PATH

RUN git clone https://github.com/friend1ws/nanomonsv.git && \
    cd nanomonsv && \
    pip3 install .

ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH

CMD ["/bin/bash"]
