FROM rocker/rstudio:4.1.0

MAINTAINER Ai Okada <aokada@ncc.go.jp>

# RUN: build
RUN apt-get -y update && \
    apt-get install -y libssl-dev libcurl4-openssl-dev libhdf5-dev &&\
    \
    Rscript -e "install.packages('ggplot2')" && \
    Rscript -e "install.packages('VennDiagram')" && \
    Rscript -e "install.packages('dplyr')"
