FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    git \
    wget \
    curl \
    bzip2 \
    make \
    cmake \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3 \
    python3-pip

RUN pip3 install numpy pysam

WORKDIR /tools
RUN wget -q https://github.com/samtools/samtools/releases/download/1.16/samtools-1.16.tar.bz2 && \
    tar jxvf samtools-1.16.tar.bz2 && \
    cd samtools-1.16/htslib-1.16 && ./configure && make && make install && \
    cd ../ && ./configure --without-curses && make && make install
    
RUN mkdir CAMPHORsomatic && \
    cd CAMPHORsomatic && \
    git init && \
    git remote add origin https://github.com/afujimoto/CAMPHORsomatic.git && \
    git fetch origin 7ad6bdb358faf1f9f52ef45e451b1842988914bb && \
    git reset --hard FETCH_HEAD && \
    wget -q https://raw.githubusercontent.com/ncc-ccat-gap/module_box_aokad/master/20220902-CAMPHORsomatic/SB_CH.patch && \
    git apply SB_CH.patch && \
    mkdir data && \
    curl -s -L http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz | zcat | grep Simple_repeat | gzip -c > ./rmsk.txt.gz && \
    curl -s -LO http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz && \
    curl -s -LO http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz && \
    curl -s -LO http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/chainSelf.txt.gz && \
    zcat ./rmsk.txt.gz | python3 ./src/repeat/rmsk.py /dev/stdin > data/rmsk.txt && \
    zcat ./simpleRepeat.txt.gz | python3 ./src/repeat/simpleRepeat.py /dev/stdin | sort -k1,1 -k2,2g > data/simplerepeat.txt && \
    zcat ./genomicSuperDups.txt.gz | python3 ./src/repeat/seg_dup.py /dev/stdin | sort -k1,1 -k2,2g > data/seg_dup.txt && \
    zcat ./chainSelf.txt.gz | python3 ./src/repeat/ucsc_selfchain.py /dev/stdin | sort -k1,1 -k2,2g > data/chainSelf.txt
