FROM python:2.7.14
MAINTAINER aokada <aokada@ncc.go.jp>

# RUN: build
RUN apt-get -y update && \
    apt-get install -y wget unzip &&\
    \
    wget https://github.com/aokad/ecsub/archive/v0.0.9.zip && \
    unzip v0.0.9.zip && \
    rm -f v0.0.9.zip && \
    cd ecsub-0.0.9 && \
    python setup.py build install

CMD ["/bin/bash"]
