FROM r-base:3.6.1
MAINTAINER aokad <aokada@ncc.go.jp>

RUN apt-get -y update
RUN apt-get install -y git libxml2-dev libcurl4-openssl-dev libssl-dev libpcre++-dev python
RUN Rscript -e "install.packages('BiocManager')"
RUN Rscript -e "BiocManager::install('SRAdb', update = TRUE, ask=FALSE)"

RUN Rscript -e "install.packages('tidyverse')"
RUN Rscript -e "install.packages('littler')"
RUN Rscript -e "install.packages('devtools')"
RUN Rscript -e "devtools::install_github('friend1ws/SF3B1ness')"

RUN git clone https://github.com/friend1ws/SF3B1_project.git
    
CMD ["/bin/bash"]
