FROM ubuntu:18.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    wget \
    python3 \
    python3-pip

RUN wget https://github.com/ncc-ccat-gap/GCATWorkflow/archive/refs/heads/master.zip && \
pip3 install master.zip

CMD ["/bin/bash"]
