#FROM ubuntu:20.04
FROM aokad/juncmut-paper:0.0.1
MAINTAINER aokada <aokada@ncc.go.jp>

RUN mkdir mutalyzer && \
    cd mutalyzer && \
    git init && \
    git remote add origin https://github.com/mutalyzer/mutalyzer.git && \
    git fetch origin b313463a31ad84e177d6d3ce7372e122f6817936 && \
    git reset --hard FETCH_HEAD && \
    pip install .
