#FROM ubuntu:20.04
FROM r-base:4.2.2
MAINTAINER aokada <aokada@ncc.go.jp>

#ENV TZ=Asia/Tokyo
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    git \
    wget \
    bzip2 \
    make \
    gcc \
    pigz \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libhdf5-dev \
    libxml2-dev \
    libcairo2-dev \
    libxt-dev \
    python3 \
    python3-dev \
    python3-pip

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /tool
RUN wget -q https://sourceforge.net/projects/samtools/files/samtools/1.16/samtools-1.16.tar.bz2 && \
    tar xjvf samtools-1.16.tar.bz2 && \
    rm -f samtools-1.16.tar.bz2 && \
    cd samtools-1.16 && \
    ./configure --without-curses && \
    make && make install

RUN wget https://github.com/samtools/bcftools/releases/download/1.16/bcftools-1.16.tar.bz2 && \
    tar xjvf bcftools-1.16.tar.bz2 && \
    rm -f bcftools-1.16.tar.bz2 && \
    cd bcftools-1.16 && \
    ./configure && \
    make && make install

RUN wget -nc https://sourceforge.net/projects/samtools/files/samtools/1.16/htslib-1.16.tar.bz2 && \
    tar xjvf htslib-1.16.tar.bz2 && \
    rm -f htslib-1.16.tar.bz2 && \
    cd htslib-1.16 && \
    ./configure && \
    make && make install

RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.30.0/bedtools-2.30.0.tar.gz && \
    tar -zxvf bedtools-2.30.0.tar.gz && \
    rm -f bedtools-2.30.0.tar.gz && \
    cd bedtools2 && \
    make && make install
    
RUN mkdir -p ucsc_tools && \
    cd ucsc_tools && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToTwoBit && \
    chmod +x faToTwoBit && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/twoBitInfo && \
    chmod +x twoBitInfo && \
    wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/blat/blat && \
    chmod +x blat && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faSplit && \
    chmod +x faSplit && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/liftUp && \
    chmod +x liftUp && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/axtChain && \
    chmod +x axtChain && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainMergeSort && \
    chmod +x chainMergeSort && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainSplit && \
    chmod +x chainSplit && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chainNet && \
    chmod +x chainNet && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/netChainSubset && \
    chmod +x netChainSubset && \
    wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/liftOver && \
    chmod +x liftOver
ENV PATH $PATH:/tool/ucsc_tools

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install cython
RUN pip3 install pysam
RUN pip3 install pandas
RUN pip3 install Bio

RUN Rscript -e "install.packages('RColorBrewer')" && \
    Rscript -e "install.packages('VennDiagram')" && \
    Rscript -e "install.packages('cowplot')" && \
    Rscript -e "install.packages('dplyr')" && \
    Rscript -e "install.packages('forcats')" && \
    Rscript -e "install.packages('futile')" && \
    Rscript -e "install.packages('ggplot2')" && \
    Rscript -e "install.packages('ggsci')" && \
    Rscript -e "install.packages('grid')" && \
    Rscript -e "install.packages('gridExtra')" && \
    Rscript -e "install.packages('gtable')" && \
    Rscript -e "install.packages('tidyr')" && \
    Rscript -e "install.packages('tidyverse')" && \
    Rscript -e "install.packages('Cairo')" && \
    Rscript -e "install.packages('wesanderson')" && \
    Rscript -e "install.packages('ggseqlogo')" && \
    Rscript -e "install.packages('BiocManager')" && \
    Rscript -e "BiocManager::install('ComplexHeatmap')"

RUN mkdir mutalyzer && \
    cd mutalyzer && \
    git init && \
    git remote add origin https://github.com/mutalyzer/mutalyzer.git && \
    git fetch origin b313463a31ad84e177d6d3ce7372e122f6817936 && \
    git reset --hard FETCH_HEAD && \
    python3 pip install .

CMD ["/bin/bash"]
