FROM ubuntu:20.04
MAINTAINER Ai Okada <aokada@ncc.go.jp> 

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
    wget \
    bzip2 \
    make \
    cmake \
    gcc \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python \
    python3 \
    python3-pip

RUN wget https://github.com/arq5x/bedtools2/releases/download/v2.30.0/bedtools-2.30.0.tar.gz && \
    tar -zxvf bedtools-2.30.0.tar.gz && \
    cd bedtools2 && \
    make && make install

RUN wget -q https://github.com/cortes-ciriano-lab/savana/archive/refs/tags/1.0.3.tar.gz && \
    tar xvf 1.0.3.tar.gz && \
    cd savana-1.0.3 && \
    pip3 install -r requirements.txt && \
    python3 -m pip install . -vv
    
