name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      dockerimage:
        description: 'user/image:tag'
        required: true
      dockerfile:
        description: 'path/to/dockerfile.txt'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build the Docker image
      run: |
        docker build . --file ${{ github.event.inputs.dockerfile }} --tag ${{ github.event.inputs.dockerimage }}
        docker push ${{ github.event.inputs.dockerimage }}
  
